title: Billignin
description: A journey to Belley and Culoz to see where Gertrude Stein and Alice B. Toklas walked their dogs.
author: Michael T. H. Scott
theme: minima
collections:
  Billignin:
    output: true
